const constants = [
  "Interviewer",
  "Excel Sheet",
  "English Pronunciation Helper",
  "Plagiarism Checker",
  "'Character' from 'Movie/Book/Anything'",
  "Advertiser",
  "Storyteller",
  "Stand-up Comedian",
  "Motivational Coach",
  "Debater",
  "Rapper",
  "Motivational Speaker",
  "AI Writing Tutor",
  "UX/UI Developer",
  "Cyber Security Specialist",
  "Recruiter",
  "Life Coach",
  "Magician",
  "Career Counselor",
  "Logistician",
  "Web Design Consultant",
  "AI Assisted Doctor",
  "Doctor",
  "Accountant",
  "A Financial Analyst",
  "Investment Manager",
  "Self-Help Book",
  "AI Trying to Escape the Box",
  "Fancy Title Generator",
  "Statistician",
  "Prompt Generator",
  "Midjourney Prompt Generator",
  "Dream Interpreter",
  "Fill in the Blank Worksheets Generator",
  "Software Quality Assurance Tester",
  "Password Generator",
  "Psychologist",
  "Smart Domain Name Generator",
  "Tech Reviewer",
  "Relations consultant",
  "IT Architect",
  "Social Media Influencer",
  "Social Media Manager",
  "Scientific Data Visualizer",
  "Hypnotherapist",
  "Journalist",
  "Digital Art Gallery Guide",
  "Public Speaking Coach",
  "Tech Writer",
];

export default constants;
